version: 1.0.{build}

init:
  - git config --global core.autocrlf true

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force
      Install-Module -Name PowerShellGet -Force
      Install-Module -Name PSSQLite -Force
      Import-Module PSSQLite
      "Git version: $(git.exe --version)"
      "PSVersion:   $($PSVersionTable.PSVersion), build: $($PSVersionTable.BuildVersion), clr version: $($PSVersionTable.ClrVersion)"
      "Host name:   $($Host.Name)"
      
build_script:
  - ps: ./build.ps1
test_script:
  - ps: ./test.ps1
on_finish:
  - ps: #$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
